#PRACTISING INPUT/OUTPUT DOUBT.
age = 21
user_age = print(age)
print(age)
#REVISIT CHATGPT FOR THIS A GOOD TOPIC WAS DAMN CONFUSED IN IT. PRINT FUNCTION WORKING. 
# take above as a example.
#AS WE TAKE THE ABOVE CODE AS EXAMPLE, 
# (1) THE PYHTON ALWAYS READ CODE FROM RIGHT TO LEFT.
#(2) SO FIRST IT WILL READ 21 WHICH IS A NUMBER THEN IT WILL SEE = AND THNE AGE SO 21 ASSIGNED TO VARIABLE AGE. 
#THEN IT WILL COME TO NEXT LINE WHICH IS LINE 3, HERE IT WILL FIRST PRINT AGE AS FROM RIGHT TO LEFT, NOW HERE'S WHAT WE HAVE TO UNDERSTAND THE DIFFERENCE BETWEEN RETURNING THE VALUE AND PRINTING THE VALUE.
#PRINTING VALUE IS FOR HUMANS TO SEE WHAT OUTPUT OUR PROGRAM IS GIVING AND RETURNING IS FOR CODE. 
#NOW PYTHON WILL PRINT AGE AS 21 AND THEN IT WILL GO BACK TO user_age = and print is returing no value to it so it values is none. 
#you can understand it more good with container example.
#and then it is print(age) so 21
# now output will 21 21. 
# you will understand return better in user defined functions more better.